export const CWB = {
  token: "CWB-34AC2BFB-2272-41E3-84FE-AAF40C0C42AA",
  host: "https://opendata.cwb.gov.tw",
  datastore: {
    weather: {
      apiPath: "api/v1/rest/datastore/O-A0003-001",
      elementName: [
        "TIME",
        "ELEV",
        "WDIR",
        "WDSD",
        "TEMP",
        "HUMD",
        "PRES",
        "24R",
        "H_FX",
        "H_XD",
        "H_FXT",
        "H_F10",
        "H_10D",
        "H_F10T",
        "H_UVI",
        "D_TX",
        "D_TXT",
        "D_TN",
        "D_TNT",
        "D_TS",
        "VIS",
        "Weather",
      ],
    },
    precipitation: {
      apiPath: "api/v1/rest/datastore/O-A0002-001",
      elementName: [
        "ELEV",
        "RAIN",
        "MIN_10",
        "HOUR_3",
        "HOUR_6",
        "HOUR_12",
        "HOUR_24",
        "NOW",
      ],
    },
    forecast: {
      apiPath: "api/v1/rest/datastore/F-D0047-091",
      elementName: [
        "MinCI",
        "MaxAT",
        "MaxCI",
        "MinT",
        "UVI",
        "MinAT",
        "MaxT",
        "WS",
        "WD",
        "Td",
        "PoP12h",
        "T",
        "RH",
        "Wx",
        "WeatherDescription",
      ],
    },
  },
};
